#!/bin/bash


_kiara_zip () {
    if [[ $GIT_REPO ]]
    then
        echo "https://github.com/${GIT_REPO}/archive/master.zip"
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tLzg4OGp1bGlib3QvS2lhcmFVc2VyQm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}

_library () {
    if [[ $BOT_LIBRARY == "pyrogram" ]]
    then 
        python3 -m PyrogramKiara
    else
        python3 -m KiaraUserBot
    fi
}

_starter () {
    local kiarapath
    kiarapath="Plugins.zip"
    echo "••• DOWNLOADING HELLBOT •••"
    wget -q $(_kiara_zip) -O "$kiaralpath"
    KIARAPATH=$(zipinfo -1 "$kiarapath" | grep -v "/.");
    unzip -qq "$kiarapath"
    rm -rf "$kiarapath"
    cd $KIARAPATH
    python3 ../updater.py ../requirements.txt requirements.txt
    echo "••• STARTING KIARABOT •••"
    _library
}

_starter
